src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La réservation doit se faire au format date (sa me parrais logique !)")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La réservation doit se faire au format date (sa me parrais logique !)")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAd;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback appellé à chaque fois qu'on créé une réservation
     * 
     * @ORM\PrePersist
     *
     * @return void
     */
    public function prePersist(){
        if(empty($this->createdAd)){
            $this->createdAd = new \DateTime();
        }
        if(empty($this->amount)){
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration(){
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAd(): ?\DateTimeInterface
    {
        return $this->createdAd;
    }

    public function setCreatedAd(\DateTimeInterface $createdAd): self
    {
        $this->createdAd = $createdAd;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate' , DateType::class , 
            ['widget' => 'single_text'],
            $this->getConfigurationFormulaire("Date d'arrivée" , "1 janvier 2019"))
            ->add('endDate' , DateType::class , 
            ['widget' => 'single_text'],
            $this->getConfigurationFormulaire("Date de départ" , "5 janvier 2019"))
            ->add('comment' , TextareaType::class,
            $this->getConfigurationFormulaire(false , "Vous pouvez saisir un commentaire"))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Form\BookingType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ad/{slug}/book", name="booking_create")     
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad , Request $request , ObjectManager $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class , $booking);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $user = $this->getUser();
            $booking->setBooker($user)
                    ->setAd($ad);

            $manager->persist($booking);
            $manager->flush();

            return $this->redirectToRoute('booking_show', ['id' => $booking->getId() , 'withAlert' => true]);
        }
        
        return $this->render('booking/booking.html.twig', [
            'ad' => $ad,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Affiche la vue de réservation effectuée
     * 
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     * @return Response
     */
    public function show(Booking $booking){
        return $this->render('booking/show.html.twig' , [
            'booking' => $booking,
        ]);
    }
}

templates/booking/booking.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver un bien{% endblock %}

{% block body %}
    <div id="bgBooking"></div>
    <div class="container mt-5">
        <h1>Réserver le bien {{ ad.title }} </h1>
        <p>Vous êtes sur le point de réserver la location du bien {{ad.title}}. Se bien appartien à
        {{ad.author.firstName}} {{ad.author.lastName}} </p>


        <div class="row mt-5 text-center">
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                  <img class="card-img-top " src="../../img/london-reserv.jpg" alt="Card image cap">
                     <div class="card-body">
                         <p class="card-text">Envie de découvrir Londres</p>
                     </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                <img class="card-img-top img-fluid" src="../../img/paris-reserv.jpg" 
                alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">Envie de découvrir Paris !</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                <img class="card-img-top img-fluid" src="../../img/rome-reserv.jpg" 
                alt="Card image cap">
                    <div class="card-body">
                     <p class="card-text">Envie de découvrir Rome</p>
                    </div>
                </div>
            </div>
        </div>

        {{form_start(form)}}
        <div class="alert alert-light formBooking">
            <h2>Séléctionnez vos dates</h2>
            <div class="row mt-5">
            <div class="col">
                {{form_row(form.startDate)}}
            </div>
            <div class="col">
                {{form_row(form.endDate)}}
            </div>
            </div>
        </div>
           <p>Le montant du séjour s'élève à : <span id="amount">...</span> &Euros <br>
           <span id="days">0</span> nuit(s) à {{ad.price}} /nuits</p>
            
            {{form_row(form.comment)}}

            <p>Envie de s'évader, de se réunir entre amis où d'organiser un séminaire d'entreprise. Nous sommes
            là pour vous accompagner !</p>

            <button type="submit" class="btn btn-success">Je réserve</button>
        

        {{form_end(form)}}
    </div>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}
{% block title %} Réservation n° {{booking.id}} {% endblock %}
{% block body %}
    <div id="bgBooking"></div>
    <div class="container mt-5">
        <h1>Voici le détail de la réservation n° {{booking.id}} </h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <p>Votre réservation {{booking.id}} à bien été pris en compte.<br>
                Pour tout renseignement vous pouvez contacter notre service client au 0800 43 44 32. <br>
                Nous vous remercions pour votre confiance
                </p>
            </div>
        {% endif %}

        <div class="row mt-5">
            <div class="col">
                <h2>Détail</h2>
                <div class="reservation mt-5">
                    <dl class="row">
                        <dt class="col-md-8">Numéro</dt>
                        <dd class="col-md-4"> {{booking.id}} </dd>
                        <dt class="col-md-8">Date d'arrivée</dt>
                        <dd class="col-md-4"> {{booking.startDate | date('d/m/Y')}} </dd>
                        <dt class="col-md-8">Date de départ</dt>
                        <dd class="col-md-4"> {{booking.endDate | date('d/m/Y')}} </dd>
                        <dt class="col-md-8">Nombre de nuit(s)</dt>
                        <dd class="col-md-4"> {{booking.duration}} </dd>
                        <dt class="col-md-8">Montant total</dt>
                        <dd class="col-md-4"> {{booking.amount}} &euro; </dd>
                        <dt class="col-md-8">Commentaires</dt>
                        <dd class="col-md-4"> {{booking.comment}} </dd>
                    </dl>
                    <hr>
                    <h2>Votre hôte</h2>
                    <div class="row hoteReservation">
                        <div class="col-md-3">
                            <img src=" {{booking.ad.author.picture}}" alt="" 
                            style="width:90px; border-radius:50%;">
                        </div>
                        <div class="col-md-9">
                            <a href=" {{path('user_show' , {'slug' : booking.ad.author.slug})}}"> 
                            {{booking.ad.author.firstName}} {{booking.ad.author.lastName}}</a>
                            <br>
                            <span class="badge badge-primary"> {{booking.ad | length }} annonces </span>
                        </div>
                    </div>
                    <p>{{booking.ad.author.description | raw}}</p>
                    <br>
                    <a href=" {{path('user_show' , {'slug' : booking.ad.author.slug })}} " class="btn btn-info">
                    Plus d'info votre hôte</a>
                </div>
            </div>
            <div class="col">
                <h2>Votre hébergement</h2>
                <img src="../img/img-london.jpg" class="img-fluid">
                <p class="mt-5"> {{booking.ad.content | raw}} </p>
            </div>
        </div>
    
    </div>

{% endblock %}